---
# Documentation: https://sourcethemes.com/academic/docs/managing-content/

title: "Potato Trade"
slug: "potato-trade"
subtitle: ""
summary: ""
authors: [admin]
tags: ["R", "R Markdown", "data", "agro"]
categories: ["Agro"]
date: '`r format(Sys.Date())`'
lastmod: '`r format(Sys.Date())`'
featured: false
bibliography: references.bib
draft: true

# Featured image
# To use, add an image named `featured.jpg/png` to your page's folder.
# Focal points: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.
image:
  caption: ""
  focal_point: "Smart"
  preview_only: false

# Projects (optional).
#   Associate this post with one or more of your projects.
#   Simply enter your project's folder or file name without extension.
#   E.g. `projects = ["internal-project"]` references `content/project/deep-learning/index.md`.
#   Otherwise, set `projects = []`.
projects: ["agro-blog"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
# Read in modules
library(tidyverse)
library(magrittr)
library(knitr)
library(kableExtra)
library(plotly)
library(scales)
```

## Data


```{r import-data, cache=TRUE, message=FALSE, echo=TRUE}
# Read in the data from csv file, store as "raw_data" - not to be overwritten
raw_data <- read_csv("../data/FAO_potato_trade.csv", guess_max = 5000, local = locale(encoding = "latin1")) %>% as_tibble()
raw_data %>% head(10) %>% kable(caption = "Raw Data from FAO") %>% kable_styling(full_width = T, bootstrap_options = c("responsive"))
```

As you can see in the last two columns of this data frame, some observations are marked with a flag. 

```{r drop-flags}
allFlags <- distinct(raw_data, Flag)

# Filter out the flagged observations and drop the Flag and Flag description columns
working_data <- raw_data %>% filter(is.na(Flag)) %>% subset(select = -c(Flag, `Flag Description`))
```

```{r trade-balance}
showQuantityBalance <- function(countries) {
  balance <- working_data %>% filter(Area %in% countries & Item == "Potatoes") %>%
    pivot_wider(id_cols = c(Area, Year), names_from = Element, values_from = Value) %>%
    mutate(
      quantity_balance = `Export Quantity` - `Import Quantity`,
      value_balance = `Export Value` - `Import Value`
    )
  balance %>% ggplot(mapping = aes(Year, quantity_balance, color = Area)) + geom_smooth(se=FALSE) +   scale_y_continuous(labels = comma) +  
    ggtitle("Net exports/imports of Potatoes (Tons)") + ylab("Tons") + coord_cartesian(xlim = c(1960, 2020))
}

showQuantityBalance(c("United States of America", "Peru", "Bolivia (Plurinational State of)"))
```

```{r import-export}
showImportsExports <- function(countries) {
  data <- working_data %>% filter(Area %in% countries & Item == "Potatoes" & Element %in% c("Import Quantity", "Export Quantity"))
  data %>% ggplot(mapping = aes(Year, Value, color = Element)) + geom_smooth(se = FALSE) + facet_wrap(~ Area) + coord_cartesian(xlim = c(1960, 2020))
}

showImportsExports(c("United States of America", "Peru"))
```

```{r camote-papa}
working_data %>% filter(Area == "Peru" & Element == "Export Quantity") %>%
  ggplot(mapping = aes(Year, Value, color = Item)) + geom_point() + geom_smooth(se = FALSE) + ylab("Export Quantity (tons)")
```

