---
title: Welcome!
author: Will Smith
date: '2020-05-11'
slug: welcome
categories:
  - Agro
tags:
  - story
subtitle: ''
summary: ''
authors: [admin]
lastmod: '2020-05-11T22:20:01-05:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

My name is Will Smith, and I am a rising senior at Davidson College, where I'm pursuing a major in Economics with an additional focus in Applied Mathematics. Approaching my final year of college, I wanted to extend my knowledge and skills in these fields with some published work available online. Thus, I have decided this summer to pursue a data science blog covering topics in agriculture, especially their economic implications. 

## Background - Why Agriculture?
I have long been interested in farming and agriculture, for their obvious role in bringing food and other necessary items to the tables of the world. When I was younger, I had the opportunity to travel with my family to Iowa, where my grandfather owns a corn and soybeans farm.  I'm sure my younger self was just ready to get out of the car after hours of driving through fields, but I appreciate having this experience observing a small part of big agriculture first-hand.  

In Fall 2019, when I studied abroad in Peru, I took a course at the Pontificia Universidad Católica del Perú called "Economía Agraria" (Agrarian Economics).  This course proved very difficult, as the professor was discussing pretty advanced material at a fast pace for three hours at a time, and I was one of only two non-native Spanish speakers in the class. Nonetheless, it was fascinating to learn about and research the intricacies of agricultural systems in Peru.  

This past spring, I took part in Davidson's Liberal Arts in Silicon Valley program, in which I developed a lot of new skills in Javascript and other web development languages.  I learned how to build functional web pages and web apps, such as a crowd-sourced thesaurus, an online recipe box, and a intra-campus communication app.  This new ability to create content online gave me the desire to continue putting things out there for people to see my work.  

Having some experience with data science in R from a course in Spring 2018, I decided to start this blog to bring together my interests in economics and agriculture and my skills and abilities to create and publish content online.  Enjoy!

## Tools and Sites Used
I am generating the content for this blog through a combination of R Markdown, Blogdown, and Hugo.  The site is published to a Netlify site, which serves my personal tech and data science domain [bitsWS](https://bits.wesmith4.com).  At least for now, all of the data I will be using comes from [FAOSTAT](http://www.fao.org/faostat/en/#home).


